pid: /var/run/thin/thin-wbrp.pid
group: wbrp
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
user: calendar
socket: /tmp/thin-wbrp.sock
chdir: /home/wbrp/wbrp